### ISSUE TITLE
pcntl_fork php function

### ISSUE THREAD

**Issue by billystalnaker** [bigicoin/SlackBuu#1]
Not sure if this is just my machine or what, but I get an error saying "Fatal error: Call to undefined function pcntl_fork()"

**Comment by billystalnaker** [comment]
Yea, it's just my machine my apologies.. It appears that function is disabled on my machine, through hostgator. Any way to get around that?

**Comment by bigicoin** [comment]
Hi billystalnaker,

Yeah, I can imagine that certain shared hosting providers would disable that. Its usage is to create a new process that runs code separately from the main process. (similar to multi threading)

SlackBotUser relies on it in order to get around having to require libraries like React php, to stay light-weight. It uses pcntl_fork() to split into 2 processes, one responsible for blocking on receive() to receive messages from Slack WebSockets, and one for sending keepalive pings to Slack + sending messages. (since receive() is blocking, it would not be able to pause to send pings every X seconds)
